development:
  adapter: postgresql
  encoding: unicode
  database: trestle_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: trestle_test
  pool: 5
  password: