development:
  adapter: postgresql
  encoding: unicode
  database: pinguin_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pinguin_test
  pool: 5
  password: